logging:
  level: INFO
  loggers:
    com.redislabs.university: DEBUG
defaultName: "RediSolar"
redis:
  host: localhost
  port: 6379
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 6391
  adminConnectors:
    - type: http
      port: 6392

